/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Farisya
 */
public class pasarmap extends javax.swing.JFrame {

    /**
     * Creates new form pasarmap
     */
    public pasarmap() {
        initComponents();
    }

    public void klikToko(ActionListener action) {
        this.tokojual.addActionListener(action);
    }

    public void klikKedai1(ActionListener action) {
        this.pasarbuah.addActionListener(action);
    }

    public void klikKedai2(ActionListener action) {
        this.kedai2.addActionListener(action);
    }

    public void klikSupermarket(ActionListener action) {
        this.supermarket.addActionListener(action);
    }

    public void klikKembali(ActionListener action) {
        this.back.addActionListener(action);
    }

    public void setUang(String a) {
        this.uang.setText(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uang = new javax.swing.JLabel();
        tokojual = new javax.swing.JButton();
        supermarket = new javax.swing.JButton();
        pasarbuah = new javax.swing.JButton();
        kedai2 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uang.setFont(new java.awt.Font("DFPOP1-W9", 0, 36)); // NOI18N
        getContentPane().add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 30));

        tokojual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/tokojual.png"))); // NOI18N
        tokojual.setBorder(null);
        tokojual.setContentAreaFilled(false);
        tokojual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tokojual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tokojualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tokojualMouseExited(evt);
            }
        });
        getContentPane().add(tokojual, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 330, 260));

        supermarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/supermarket.png"))); // NOI18N
        supermarket.setBorder(null);
        supermarket.setBorderPainted(false);
        supermarket.setContentAreaFilled(false);
        supermarket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supermarket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supermarketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supermarketMouseExited(evt);
            }
        });
        getContentPane().add(supermarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 310, 240));

        pasarbuah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/pasarbuah.png"))); // NOI18N
        pasarbuah.setBorder(null);
        pasarbuah.setBorderPainted(false);
        pasarbuah.setContentAreaFilled(false);
        pasarbuah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pasarbuah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pasarbuahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pasarbuahMouseExited(evt);
            }
        });
        getContentPane().add(pasarbuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 380, 510));

        kedai2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/pasarbuah2.png"))); // NOI18N
        kedai2.setBorder(null);
        kedai2.setBorderPainted(false);
        kedai2.setContentAreaFilled(false);
        kedai2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kedai2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kedai2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kedai2MouseExited(evt);
            }
        });
        getContentPane().add(kedai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 470, 420));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/back.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 120, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/mappasar.png"))); // NOI18N
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasarbuahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasarbuahMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/pasarbuahover.png"));
        pasarbuah.setIcon(hover);
    }//GEN-LAST:event_pasarbuahMouseEntered

    private void pasarbuahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasarbuahMouseExited
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/pasarbuah.png"));
        pasarbuah.setIcon(hover);
    }//GEN-LAST:event_pasarbuahMouseExited

    private void supermarketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supermarketMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/supermarkethover.png"));
        supermarket.setIcon(hover);
    }//GEN-LAST:event_supermarketMouseEntered

    private void supermarketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supermarketMouseExited
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/supermarket.png"));
        supermarket.setIcon(hover);
    }//GEN-LAST:event_supermarketMouseExited

    private void tokojualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tokojualMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/tokojualhover.png"));
        tokojual.setIcon(hover);
    }//GEN-LAST:event_tokojualMouseEntered

    private void tokojualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tokojualMouseExited
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/tokojual.png"));
        tokojual.setIcon(hover);
    }//GEN-LAST:event_tokojualMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/backhover.png"));
        back.setIcon(hover);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/back.png"));
        back.setIcon(hover);
    }//GEN-LAST:event_backMouseExited

    private void kedai2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kedai2MouseEntered
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/pasarbuah2hover.png"));
        kedai2.setIcon(hover);
    }//GEN-LAST:event_kedai2MouseEntered

    private void kedai2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kedai2MouseExited
        ImageIcon hover = new ImageIcon(getClass().getResource("/ui export/pasarbuah2.png"));
        kedai2.setIcon(hover);    }//GEN-LAST:event_kedai2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasarmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasarmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasarmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasarmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasarmap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton kedai2;
    private javax.swing.JButton pasarbuah;
    private javax.swing.JButton supermarket;
    private javax.swing.JButton tokojual;
    private javax.swing.JLabel uang;
    // End of variables declaration//GEN-END:variables
}
